language: bash
os: windows
env:
  global:
    - VSCMDPATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools"
script:
  - cd "$VSCMDPATH" && cmd "/K "VsDevCmd.bat" & powershell" 
  - msbuild
branches:
  only:
    - develop  
    - "/^v\\d.*/"
