language: python
env:
- SETUPTOOLS_SCM_PRETEND_VERSION=$TRAVIS_TAG
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
branches:
  only:
  - develop
  - "/feature\\/.*/"
  - "/^v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$/"

deploy:
  name: $TRAVIS_TAG
  body: New version $TRAVIS_TAG available
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OO942cRHDc3MdOV7Ngs247Wv81Qq6G24k4aoq55cXlZQyQ5Slsrdm7ynN4eJcXZM2WQj1gLYrqVH7TVKkZlLMewzn+gTrJSQ5ED8hmPEX9DBysL8iJG2YaVy87fkXAOkZ4PM0O7kJuj7dP9AJHac04xQ+Jga1lZu4RaiNl8WWU/JJmiOmPBbMs2hFmolcbppj4oEFKBIl8Yd8/qJYYniwJC0tQSWfO7qO8Pknc3h0oixKfUXaKuXVT0M8aEwToCvNB7Jx5Ck0A+XWL34fboUCqy0bSjji/8jTo1bIrLxe0wP1c6YEFMe1pExYjPTqh6/fGJ33R2YbBjQsNPlVOPovjq+sYAtQJkrb9KZZQBXvYbx8160eW+OY4QEDvUnJhyVpfCLKoWBYaXPJ2HVyiGqyIwLYGMJZKAu1lshUPi9ZzQV+akVx+oErjqy9PTnmkNVnw3llR/MGLi1C0JL8iEh6cLqCeDRR9sjUcjE/oaAWcIaJs3MrvyDztm0Um59ZDRjmbSMZw0SfYcHdM9g2k++SnB4GixqwjErHeTzhoPe+mY6v5M3rG2x++rkmDypB51TyE18lkMJw1WiROBhCTA9QffxmWGmaNT/40BDYWvtfmrAWPmDibc5YL80LrLVlzsxUYGAUh1xC1q21aeL9odU7wYwPVNsEd+7D/rSmh4Zv7s=
  file_glob: true
  file: dist/*
  draft: true
  on:
    tags: true
